### ISSUE TITLE
Mapping of Lambda layer and project versions

### ISSUE THREAD

**Issue by tmatilai** [hashicorp/vault-lambda-extension#118]
Is there or could there be some way of mapping the Lambda layer versions to the release/tag versions of the repository? In the readme, release notes, somewhere else?

**Comment by fairclothjm** [comment]
@tmatilai Should be done now for the past 3 release. You can find the layers listed on the Changelog and the Release notes for a given release

**Comment by tmatilai** [comment]
Thanks a lot! 🤗
