### ISSUE TITLE
Publish extension in ap-south-2

### ISSUE THREAD

**Issue by andrewjharms** [hashicorp/vault-lambda-extension#124]
I'm getting an access denied error when attempting to deploy a Lambda function to the ap-south-2 region that has a dependency on this extension:

```
Error: creating Lambda Function (MyLambda): operation error Lambda: CreateFunction, https response error StatusCode: 403, RequestID: xxxxxxxx, api error AccessDeniedException: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/xxxxxxxxxx/aws-go-sdk-xxxxxxxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-south-2:634166935893:layer:vault-lambda-extension:17 because no resource-based policy allows the lambda:GetLayerVersion action
```

I suspect this is because the extension has not been made available in the newer ap-south-2 region. Looking at the README, ap-south-2 is not listed as an available region in the ARN string. Please make this extension available to all AWS regions.

**Comment by raymonstah** [comment]
The layer for VLE has been published to ap-south-2. Here's the ARN: `arn:aws:lambda:ap-south-2:634166935893:layer:vault-lambda-extension:1`
