### ISSUE TITLE
Trouble Deploying Extension as Lambda Layer

### ISSUE THREAD

**Issue by jimifredjr** [hashicorp/vault-lambda-extension#153]
I'm trying to test the recent fix for snapstart by Deploying the latest repo changes

Steps Recreate
Clone the repo
Run `go build -o vault-extension`
Zip up the vault-extension executable
Upload zip to S3
Deploy zip as a new Lambda layer
---> Here AWS throws an error since the zip is over 100mb

**Comment by jimifredjr** [comment]
Do you know when the next release is planned for?

**Comment by fairclothjm** [comment]
@jimifredjr We are planning to do a release within the next week or so. Were you able to test with snapstart?
