### ISSUE TITLE
secret.json is null

### ISSUE THREAD

**Issue by petersin0422** [hashicorp/vault-lambda-extension#25]
I was able to authenticate and received a token in `/tmp/vault/token`, however, the `/tmp/vault/secret.json` is always null. We were able to pull the same secret using the Kubernetes Vault agent, and also from the CLI using another auth method.

```Python
def lambda_handler(event, context):
    with open('/tmp/vault/secret.json', 'r') as secrets:
        secret = secrets.read()
        print(secret)
```

```
START RequestId: 51ef0403-7111-496f-b908-48e2abdcc29c Version: $LATEST
[vault-lambda-extension] 2021/01/22 00:32:18 Received event
[vault-lambda-extension] 2021/01/22 00:32:18 Waiting for event...
null
END RequestId: 51ef0403-7111-496f-b908-48e2abdcc29c
REPORT RequestId: 51ef0403-7111-496f-b908-48e2abdcc29c	Duration: 1.51 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 91 MB	Init Duration: 646.04 ms
```

**Comment by tomhjp** [comment]
Hi @petersin0422, thanks for the report, are you able to share the environment variables you have set up for the extension please, and an example CLI command that successfully retrieves the secret? The extension _should_ error and cause the whole function to fail if it fails to write to the specified file, but I'd be interested to repro this if it's not.

**Comment by petersin0422** [comment]
Thank you for the quick reply! I ran the lambda function again but this time having it returning the token as well. As you can see below, I am using the same token in the CLI and was able to fetch the data.

```
START RequestId: f5495b16-ff55-4be2-9130-734817717487 Version: $LATEST
[vault-lambda-extension] 2021/01/22 16:50:36 Received event
[vault-lambda-extension] 2021/01/22 16:50:36 Waiting for event...
null
s.bI7K7Dtdn6i1CoKHQOBOhDRK
END RequestId: f5495b16-ff55-4be2-9130-734817717487
REPORT RequestId: f5495b16-ff55-4be2-9130-734817717487	Duration: 1.67 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 91 MB	Init Duration: 654.79 ms
```

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/46800673/105520623-c62f4f00-5c8f-11eb-9a8a-6026577d4f60.png)

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/46800673/105520664-d5ae9800-5c8f-11eb-9b63-0437c0768860.png)

**Comment by tomhjp** [comment]
Sorry for the long delay here. Looks to me like there are 2 problems:

* `VAULT_SECRET_PATH` should be `kv/data/cloud/lambda-cd/git-token`, the same value as in your CLI example
* The extension uses the `api` client from the Vault SDK, which returns both `nil` error and `nil` content if it gets a 404 back from Vault. In the case of the extension, we should complain loudly and fail the function because that should never be an expected response, but instead it currently just writes an empty file.

**Comment by petersin0422** [comment]
Thank you very much for the reply! I have tested it and it works! Cheers!
