### ISSUE TITLE
Not able to use extension with go run time

### ISSUE THREAD

**Issue by karthikbhat003** [hashicorp/vault-lambda-extension#45]
Hi team,

I have lambda function which has go runtime 1.x and by this documentation able to see that it is not supported.
And I'm not able to get the secrets from vault.
Is there any timeline that can be expected in near future.?

<img width="665" alt="Screenshot 2021-07-26 at 6 25 09 PM" src="https://user-images.githubusercontent.com/50072822/126992068-fc044ef6-800a-466c-ae16-60ab9d1730c9.png">

Thanks in advance.

**Comment by tomhjp** [comment]
Hi @karthikbhat003, thanks for your interest. Unfortunately, this depends on AWS Lambda adding support for extensions to the go runtime. See https://github.com/hashicorp/vault-lambda-extension#requirements and specifically https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html.

If you'd like to run Go with extensions in Lambda, you can use one of the custom runtimes. Check out the materials in the [`quick-start`](https://github.com/hashicorp/vault-lambda-extension/tree/main/quick-start) folder to see a full end to end example of that, as the `demo-function` is written in Go.
