### ISSUE TITLE
Layer not assignable to lambda when using Terraform

### ISSUE THREAD

**Issue by kalcozar** [hashicorp/vault-lambda-extension#46]
I am using Terraform to create my Lambda in us-east-1.  If I try to include this attribute in my aws_lambda_function configuration 
`layers            = ["arn:aws:lambda:us-east-1:634166935893:layer:vault-lambda-extension:10"]` 
I get an error during terraform apply: 
`Error: error modifying Lambda Function (my-lambda-name) configuration : AccessDeniedException`

There isn't much returned in the debug output worth noting, just the 403 Forbidden.
I am able to add the layer in the console, by selecting layers... Add layer... Specify an ARN, and pasting in arn:aws:lambda:us-east-1:634166935893:layer:vault-lambda-extension:10.  When adding manually, the layer behaves as documented, however I need to be able to add it with Terraform.    Any ideas?  Thanks!

**Comment by tomhjp** [comment]
How odd! If you follow the [quick-start readme](https://github.com/hashicorp/vault-lambda-extension/tree/main/quick-start), does that work? AFAICT, that is doing exactly the same as what you are attempting, referring to the layer from terraform, and I regularly test it from an account that is not connected to the account we publish from. If that doesn't help you solve it, please could you include some more details like terraform and AWS provider versions, or ideally a patch to the quick-start terraform config that reproduces the issue for you?

**Comment by tomhjp** [comment]
Will re-open and investigate if anyone can repro this.
