### ISSUE TITLE
[ERROR] LAMBDA_RUNTIME Failed to get next invocation. Http Response code: 403

### ISSUE THREAD

**Issue by armandAkop** [hashicorp/vault-lambda-extension#48]
Node Version: 14.x
Layer ARN: arn:aws:lambda:us-west-2:634166935893:layer:vault-lambda-extension:8

Hey all, I'm not certain if this error is cause by the extension exactly, but I started running into this recently. I noticed this error popping up in my logs:

```
[ERROR] LAMBDA_RUNTIME Failed to get next invocation. Http Response code: 403
```

Immediately after, my code that would read the secret file would throw an exception that the file was not found.
Here is a snipper of my code:
```node
const secretFile = require('/tmp/vault/secret.json') // throwing Cannot find module '/tmp/vault/secret.json'
```

This seems to happen more frequently during cold starts, after a few retries, the lambda executes successfully.

TODOs for me:

- [ ] Test with new version of layer

**Comment by tomhjp** [comment]
> [ERROR] LAMBDA_RUNTIME Failed to get next invocation. Http Response code: 403

I've not seen this before, is there any context over where the 403 is coming from? Or any further error details? The error text included doesn't seem to obviously come from the extension, but I can't rule it out. And do you have a reliable way I could repro this myself?

> const secretFile = require('/tmp/vault/secret.json') // throwing Cannot find module '/tmp/vault/secret.json'

Just to double check, this code is inside the function handler code, and not part of the static function code right? i.e. this isn't the same issue as #31? The fact it's flaky and happens more during cold starts makes me suspicious it's the same race condition as #31.

**Comment by armandAkop** [comment]
@tomhjp This was my bad, I just found a rogue piece of code that was OUTSIDE of the handler function which was trying to retrieve the secrets at that location. I'll close this ticket.
