### ISSUE TITLE
Unable to read secret 

### ISSUE THREAD

**Issue by ajain0811** [hashicorp/vault-lambda-extension#51]
Hi Team,

I have added this layer in my lambda function with node js run time and executed the lambda function by adding the environment variable suggested by this extension. Getting the below response.

START RequestId: a26d616a-8046-4d39-927f-105364a34a44 Version: $LATEST
69df7b36-a7b2-4278-8a14-f168e8498010[vault-lambda-extension] 2021/08/27 12:28:19 Initialising
[vault-lambda-extension] 2021/08/27 12:28:19 authenticating to Vault
[vault-lambda-extension] 2021/08/27 12:28:19 Initialised
[vault-lambda-extension] 2021/08/27 12:28:19 Waiting for event...
[vault-lambda-extension] 2021/08/27 12:28:19 Starting HTTP server
EXTENSION	Name: vault-lambda-extension	State: Ready	Events: [SHUTDOWN,INVOKE]
[vault-lambda-extension] 2021/08/27 12:28:19 Received event
[vault-lambda-extension] 2021/08/27 12:28:19 Waiting for event...
END RequestId: a26d616a-8046-4d39-927f-105364a34a44

Here, I am not able to read the secret in node js lambda code which should be present in the extension response.
Can you please help me with this, how I can read my secret in node js by using this extension? Appreciate your help.

**Comment by ajain0811** [comment]
Hi @tomhjp, I have tried the solutions suggested by you. I have received an error for missing the "type" parameter for the function. As I am working with IAM based authentication so I also tried to provide type = iam but it didn't work as I am not able to authenticate the api: { url: 'http://16.201.xx.xx:8200' }.

Now I have moved directly with HTTP call.

So here, The payload like this without using this extension. 
const options = {
    url: 'http://16.201.xx.xx:8200/v1/kv/data/data/lambda_secret',
    method: 'GET',
    headers: {
        'Authorization': 'Bearer s.yjlxxxxxxxxxxxxxxxx',
    }
};

After using this extension my expectation is, payload should be like this.
const options = {
    url: 'http://16.201.xx.xx:8200/v1/kv/data/data/lambda_secret',
    method: 'GET'
};

Any idea on this, how can I achieve this?

**Comment by tomhjp** [comment]
I think you need to update the payload to be:

```
const options = {
  url: 'http://127.0.0.1:8200/v1/kv/data/data/creds',
  method: 'GET'
};
```

That `127.0.0.1` is the loopback address, which is how you communicate with the local proxy that is running within your function when the extension is set up. As it is, your payload is skipping the local proxy altogether and going straight to your remote Vault instance.

**Comment by ajain0811** [comment]
It worked, Thanks a lot @tomhjp.

**Comment by tomhjp** [comment]
🎉 You're welcome! Glad to help.

**Comment by mstmustisnt** [comment]
@ajain0811 how did you set up the proxy server? I was following [the guide](https://learn.hashicorp.com/tutorials/vault/aws-lambda) and it doesnt seem to create a proxy server - requests to 127.0.0.1:8200 fail with `ECONNREFUSED`
@tomhjp is there an example on how to set up the proxy server?

the logs:
```
2022-07-01T10:52:59.132+03:00 | [vault-lambda-extension] 2022/07/01 07:52:55 attemping Vault login...
2022-07-01T10:52:59.133+03:00Copy[vault-lambda-extension] 2022/07/01 07:52:59 error getting client: Put "http://127.0.0.1:8200/v1/auth/aws/login": dial tcp 127.0.0.1:8200: connect: connection refused | [vault-lambda-extension] 2022/07/01 07:52:59 error getting client: Put "http://127.0.0.1:8200/v1/auth/aws/login": dial tcp 127.0.0.1:8200: connect: connection refused
```

**Comment by tomhjp** [comment]
@mstmustisnt what version of the extension are you using? The proxy server was added in v0.3.0, or layer version 8, and it should always be available on that port, no config required. If you're already on the latest version, please could you open a new issue with more details about your setup? It might be that we've introduced a race condition recently, so I'd be interested if it's reproducible with the latest code.

**Comment by mstmustisnt** [comment]
@tomhjp yup, I noticed that the example uses extension v6, so I have updated it to 13, and now I see `Starting proxy server` in the logs. Thanks!

**Comment by tomhjp** [comment]
Awesome :) I've raised a couple of PRs (referenced above) to fix the outdated version - thanks for pointing it out!

**Comment by mstmustisnt** [comment]
@tomhjp thank you! I have another question.
Now I need to set both `VAULT_ADDR` AND `VLE_VAULT_ADDR`
Where `VAULT_ADDR` should be set to `http://127.0.0.1:8200` and `VLE_VAULT_ADDR` to `vault_server_ip`?
