### ISSUE TITLE
Extension seems not compatible with arm graviton 2 processor

### ISSUE THREAD

**Issue by jrichard8** [hashicorp/vault-lambda-extension#55]
I tried to run my lambda on an ARM architecture provided.al2 and I had an error an Vault-extension run time:

_Error: fork/exec /opt/extensions/vault-lambda-extension: exec format error_

Do you a version available for arm64 ?

**Comment by jrichard8** [comment]
I tried to built it locally with arm64 arch but it failed too at runtime. I guess it needs a bootstrap file to run extension on provided.al2 custom runtime.

**Comment by JinlianWang** [comment]
@tomhjp this has been one of our concerns as well. Can we share the plan over Graviton support?

**Comment by benMain** [comment]
Is there a reason this lib isn't implemented in an interpreted language, such that we could have avoided this situation?

**Comment by tomhjp** [comment]
Thanks for raising this - definitely a good feature request. We'll look into deploying an arm64 version too. If you'd like to re-attempt packaging it yourself in the meantime, there's nothing very special about the zip file layer. It's just a zip with a single folder `extensions`, and a single executable (as built by `go build`) in that folder `vault-lambda-extension`.

The bootstrap file you mentioned is deployed along with the function, and there's an example of a basic bootstrapper in the `bin` directory here: https://github.com/hashicorp/vault-lambda-extension/tree/main/quick-start/demo-function

**Comment by tvoran** [comment]
As of v0.7.0 we now publish binaries and layers for both amd64 (x86_64) and arm64. See the [Readme](https://github.com/hashicorp/vault-lambda-extension/blob/main/README.md) for more details.
