### ISSUE TITLE
Usability: Can we trim environment variables?

### ISSUE THREAD

**Issue by AdrienneCohea** [hashicorp/vault-lambda-extension#59]
We had a very interesting thing happen today. We're using `VAULT_AUTH_ROLE` but missed a trailing space, and as a result got a very vexacious

`Error: entry for role rolename  not found`

We checked and rechecked our Vault AWS roles in the auth method and our IAM role multiple times, but missed the extra space in the error format string. And yeah, AWS could have helped us out here by trimming the spaces in the text box for us.

But I wonder, could we trim the environment variables here? https://github.com/hashicorp/vault-lambda-extension/blob/8071362e261d315bd6a63b183494ecfdef336cc6/internal/config/auth.go#L27

**Comment by AdrienneCohea** [comment]
Curiously Github took out the extra space in my example of the error message. But you get the idea: VAULT_AUTH_ROLE was "rolename " rather than "rolename"

**Comment by tomhjp** [comment]
Hi @AdrienneCohea, thanks for raising this! Seems like a completely reasonable improvement, especially if the console UI is making it easy to misconfigure. Happy to take PRs, or otherwise I'll try to get it in for the next release, which should be coming up relatively soon.
