### ISSUE TITLE
Publish executables with a release

### ISSUE THREAD

**Issue by alexeyshockov** [hashicorp/vault-lambda-extension#91]
Hey, thanks for the extension!

Could you also publish compiled executables with every release? I'm interested in using this one in a Docker image, not as a layer.

**Comment by tomhjp** [comment]
Thanks for asking - the readme used to include instructions for this, but then the instructions moved here: https://developer.hashicorp.com/vault/docs/platform/aws/lambda-extension#step-2-option-b-install-the-extension-for-lambda-functions-packaged-in-container-images

The binaries are available here: https://releases.hashicorp.com/vault-lambda-extension/

I've also opened #92 to make sure it's easier to discover those instructions.

**Comment by alexeyshockov** [comment]
@tomhjp, thanks!

Just curious, is it possible to download `latest` release from https://releases.hashicorp.com/vault-lambda-extension/?

With Github releases I usually do it like this: `https://github.com/org_name/repo_name/releases/latest/download/...`.

**Comment by tomhjp** [comment]
We don't publish a "latest" version, but you could use the API to query it:

```shell-session
$ curl -s https://api.releases.hashicorp.com/v1/releases/vault-lambda-extension?limit=1 | jq -r '.[0].version'
0.8.0
```
